apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-database
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-database
spec:
  source:
    git:
      url: https://github.com/johnlafata/node-todo.git
      ref:
        branch: master
